# Generated by Django 5.0.9 on 2024-11-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='dog_name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='photo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth_date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'dog',
                'verbose_name_plural': 'dogs',
            },
        ),
    ]
